### ISSUE TITLE
Idea: Vehicle is Reversing Sound

### ISSUE THREAD

**Issue by Peekofwar** [Blu-x92/simfphys_base#12]
Most modern trucks and busses have a sound module that warns anyone nearby that a vehicle is about to start reversing. I think it would be cool, and add to the immersion if we could have a sound slot for a sound that would play when a vehicle is in reverse.

[Vehicle is Reversing Sounds.zip](https://github.com/Blu-x92/simfphys_base/files/1935827/Vehicle.is.Reversing.Sounds.zip)

**Comment by NotAKidOnSteam** [comment]
Ive been setting them as sirens for my semi's. That way you can toggle it by hitting the horn button.
