### ISSUE TITLE
generating LampPos vectors and angles

### ISSUE THREAD

**Issue by scunky11** [Blu-x92/simfphys_base#13]
hello! i'm not being sarcastic when i say i've been having a lot of fun assembling/tuning cars on simfphys, i've got a handle on the rest of the lua stuff but i just can't figure out how to create or find my own values for lamp positions

is there any kind of resource or command you used to atleast get a roughly accurate value that you could then tweak? how are people able to get the lights into position?

thank you for taking your time to read this, i really look forward to a response!

**Comment by cynaraos** [comment]
assuming youre talking about spawnmenu scripts or whatever theyre called
i personally just set up a regular sprite and then i copy the position from that

**Comment by SupinePandora43** [comment]
just use Easy Entity Inspector Tool, you can see where you click!
