### ISSUE TITLE
Change lights based on bodygroups?

### ISSUE THREAD

**Issue by BitCrack** [Blu-x92/simfphys_base#15]
I don't know if there is something already like that.
I am making a simfphys car based on Mitsubishi Eclipse GSX but this car has differently positioned reverse lights on different bodygroups.

**Comment by cynaraos** [comment]
![notepad _2018-07-29_15-47-59](https://user-images.githubusercontent.com/12373395/43367018-cc7c5d0e-9346-11e8-9163-cacfa8d88eac.png)
