### ISSUE TITLE
light with shape or light with custom model

### ISSUE THREAD

**Issue by SupinePandora43** [Blu-x92/simfphys_base#16]
can you provide this??? because sometimes require create square light, triangle, but create lot light values? and if stormFox can do this, can you add changing temperature in car salon

**Comment by SupinePandora43** [comment]
and simfphys.com not has new Api (setLightsEnabled() and more...)

**Comment by SupinePandora43** [comment]
what's about emergency lighting how in Photon Lighting Engine???

**Comment by Blu-x92** [comment]
i wanted to do this but at this point ist very unlikely to happen
