### ISSUE TITLE
Would any issues arise from walker vehicles?

### ISSUE THREAD

**Issue by VaasKahnGrim** [Blu-x92/simfphys_base#17]
Basically I'm currently using LFS planes for my servers air vehicles and decided I'd also replace ground vehicles aswell using the simfphys_base. however I'm somewhat wondering if ground vehicles that move via walker legs rather then wheels would potentially be any issue?

Basically I'm trying to replace several walkers from starwars with this base instead of the old vehicle base most starwars rp servers use.

**Comment by Blu-x92** [comment]
simfphys is for cars only

**Comment by SupinePandora43** [comment]
** created float base for simfpys! You can create "simfphys walker vehicles base". It's gmod, there can be anything!
