### ISSUE TITLE
Transmission Idea?

### ISSUE THREAD

**Issue by mrwallace888** [Blu-x92/simfphys_base#19]
Could it be possible to rewrite the transmission?
When using Automatic it should let off the gas when shifting, which would also do the turbo's blow-off valve sound effect (if there's a turbo on the car). And then in the Vehicle Editor/Edit Properties, maybe you can set the shift speed? Slower, older vehicles could shift at a lower rate while faster, newer vehicles shift almost instantaneously.
Just thought it'd be cool.

Also maybe gear-shift animations similar to Sakarias88's Cars? Shifting LHD, Shifting RHD, and Paddle-Shift?

This addon (or at least, the Workshop edition) hasn't been updated in a while. Maybe some newer features and fixes, or perhaps a rewrite?

**Comment by mrwallace888** [comment]
Anyone?

**Comment by AMIDIBOSS** [comment]
Mee

**Comment by Blu-x92** [comment]
Possible? Yes. Will i do it? No. 
btw most automatic cars don't let off throttle when shifting

**Comment by AMIDIBOSS** [comment]
Yeah, "classic" manuals can do without letting off the throttle because of a torque converter, and DCT transmissions shift so fast it's just pointless. Although if it's possible but you're not willing to do it, maybe it can be done by someone else (me?)

**Comment by Blu-x92** [comment]
no. I have already done this years ago and could easily do it again. It's just a small gimmick that will add nothing but problems with how the current sound system works… and i will surely not force everyone to a new sound system and adding yet another option is not a option…
At this point, you can't do any drastic changes anymore. People will complain about how their hard work is suddenly gone

**Comment by mrwallace888** [comment]
So is this addon abandoned/discontinued?
