### ISSUE TITLE
Fix the Blinker Delay?

### ISSUE THREAD

**Issue by mrwallace888** [Blu-x92/simfphys_base#20]
Will you ever change the blinker delay so that it will work properly?

Real blinkers go tick-TICK-tick-TICK-tick-TICK.

Your blinkers go tick-TICK... tick-TICK... tick-TICK...

Kinda thought about this earlier and just realized this.

**Comment by Blu-x92** [comment]
Both methods are correct and exist on real cars depending on year of manufacture / brand. Nothing wrong there.
