### ISSUE TITLE
Light table submaterials for attachments

### ISSUE THREAD

**Issue by cyckl** [Blu-x92/simfphys_base#27]
Hello, I'm the author of a simfphys car and currently it is possible to apply submaterials to the main model using the following code, but not attachments.

```lua
SubMaterials = {
    off = {
        Base = {
            [7] = "cyckl/cars/e30m3/dials",
        },
    },
    on_lowbeam = {
        Base = {
            [7] = "cyckl/cars/e30m3/dials_on",
        },
    },
    on_highbeam = {
        Base = {
            [7] = "cyckl/cars/e30m3/dials_on_high",
        },
    },
},
```

This is a problem because I have a main exterior model (`ext.mdl`) and an interior attachment (`int.mdl`). If I want to implement toggle-able interior lighting, I can't.

Can this be done right now, and if not, is this possible to implement in the future? Thanks.

**Comment by Blu-x92** [comment]
doesn't look like anyone want's to help with this. I close this issue as i have no plans in enhancing the current lighting system.
