### ISSUE TITLE
Add the "exitpos" config variable

### ISSUE THREAD

**Issue by Milou146** [Blu-x92/simfphys_base#39]
Hello, Is it possible to add the "exitpos" config variable on simfphys please? Because when I get out my transport troop vehicle I get to the top of the vehicle and we can get shot by the turret of the vehicle which is shooting enemies to cover the extraction of the soldiers. It's happening often
https://steamuserimages-a.akamaihd.net/ugc/1616185079751408687/6F92C17676E53310DC768906670575508062580F/

(sorry for my bad english)

**Comment by Blu-x92** [comment]
the vehicle exit script is trash and needs a full rework like the entire addon does. Unlikely this will ever be added. Closed.
