### ISSUE TITLE
Instant crash when a fast zombie jump attacks a simfphys driver

### ISSUE THREAD

**Issue by StrawWagen** [Blu-x92/simfphys_base#41]
Dedicated server / singleplayer session instantly crashes when a fast zombie jump attacks a player that's driving a simfphys car.

The issue has been very repeatable for me, I have lots of addons installed so the issue may be a conflict.

After discovering the issue on a dedicated server, I subsequently created a singleplayer session. When I loaded in, I spawned in a simfphys vehicle, then spawned around a dozen fast zombies. I crashed out of the session quickly after I sat in the car's driver seat.

Here's to hoping this issue is repeatable, leave a comment if you can't repeat the issue. Thanks!

**Comment by Blu-x92** [comment]
only happens for you.

**Comment by StrawWagen** [comment]
Okay, well then if it's not repeatable like you said, then it's either a conflict or something I overlooked.
I'll keep digging to see why it's happening to me and the server I found it on.

**Comment by StrawWagen** [comment]
seems to only happen if the session is running on the x64 bit branch

**Comment by StrawWagen** [comment]
@Blu-x92 just had a resurgence of this bug, I'm sorry I didn't investigate more before initially submitting this.
Most likely why this hasn't been spotted before is that the crash only seems to happen on the x64 branch.

**Comment by StrawWagen** [comment]
Still an issue on the x64 branch

**Comment by StrawWagen** [comment]
creating a new issue due to inactivity and the bug still being active
