### ISSUE TITLE
How to block: "Edit properties" on a vehicle for all players?

### ISSUE THREAD

**Issue by rayzox57** [Blu-x92/simfphys_base#42]
Hello ! How can I block the modification of vehicles entirely? Thank you ! (I'm already using WUMA to restrict the edit tool but the player can still edit with the context menu :/) Thanks!

<a href='https://www.casimages.com/i/2101070143017986.png.html' title='Mon image' target='_blank'><img src='https://nsa40.casimages.com/img/2021/01/07/mini_2101070143017986.png' border='0' alt='Mon image' /></a>

**Comment by Blu-x92** [comment]
sv_simfphys_devmode 0
menu will still be visible but not useable
