### ISSUE TITLE
Big Maps Break MassOffset

### ISSUE THREAD

**Issue by NotAKidOnSteam** [Blu-x92/simfphys_base#45]
Maps that almost reach Garrys Mod map size limitations will cause the mass offset prop attached to simfphys vehicles to freak out and get destroyed by the engine.

```
Crazy origin on entity [61][prop_physics]
	Origin:           [214.159897, 931.244446, -16452.402344]
	Angles:           [0.000000, 0.000000, 360.000000]
	Velocity:         [0.000000, 0.000000, -0.000000]
	Angular Velocity: [0.000000, 0.000000, -0.000000]
Defusing!
Removing!

[[simfphys] LUA Vehicles - Base] lua/entities/gmod_sent_vehicle_fphysics_base/spawn.lua:569: Tried to use a NULL entity!
  1. GetPhysicsObject - [C]:-1
   2. unknown - lua/entities/gmod_sent_vehicle_fphysics_base/spawn.lua:569

Timer Failed! [Simple][@lua/entities/gmod_sent_vehicle_fphysics_base/spawn.lua (line 564)]

```

Probably not anything that can be done to fix it other than maybe spawning the prop at 0,0,0 and moving it to where it should be afterward. Maybe a check for the missing physicsobject that alerts the player or server that the map is likely too big and simfphys functionality may be impacted. LFS vehicles are straight up deleted as well on some maps depending on how fast they fall to the ground after spawn.

**Comment by Blu-x92** [comment]
all props already spawn at 0,0,0 when ents.Create is called and then are moved using setpos
