### ISSUE TITLE
I can't drive simfphys vehicles on my gamemode

### ISSUE THREAD

**Issue by Porazzh** [Blu-x92/simfphys_base#46]
I modified a gamemode so i changed scars to simfphys and when im trying to drive car i cant move the engine is working but nothing else i tried this function but it doesn't work 4 me https://www.reddit.com/r/GLua/comments/gx73mx/cant_drive_simfphys_vehicles_in_my_gamemode/

**Comment by Blu-x92** [comment]
create a luafile in garrysmod/lua/autorun/server/ with this code:

hook.Add( "PlayerButtonUp", "simfphys_fixnumpads", function(ply, btn) numpad.Deactivate( ply, btn ) end)
hook.Add( "PlayerButtonDown", "simfphys_fixnumpads", function(ply, btn) numpad.Activate( ply, btn ) end)

**Comment by Porazzh** [comment]
Thanks a lot it helped
