### ISSUE TITLE
Any way I can apply these lines of codes and have it affect all simfphys cars?

### ISSUE THREAD

**Issue by mrwallace888** [Blu-x92/simfphys_base#49]
Kirbyguy told me about a thing he did for one of his cars that give cars turbo blow-off with gear shifting when these lines of code are added to the lua of the vehicle:

> I'm not sure how to make it affect all cars, but if you want the same effect, you can add this in to the car's lua script:
> 
> `local gear = 0` --add these at the beginning of the lua file
> `local gearNext = 0`
> 
> --put the rest in `OnTick = function(ent)`
> 
> ```
> gearNext = ent:GetGear()
> if (gear ~= gearNext) then
> ent:SetThrottle(0)
> end
> gear = ent:GetGear()
> ```
> 
> This cuts the throttle momentarily to force the blowoff valve sound to play. Hopefully other simfphys creators will see this and add it to their own cars.

I've done this before, but it's a hassle having to do with all the cars I want to be affected by it. But is there any way I can add this somewhere to the base mod lua itself so it affects all cars automatically? This is especially because I assume you wouldn't add it as a simfphys feature yourself, so eh.

**Comment by NotAKidOnSteam** [comment]
Some vehicles will probably conflict with this if it were to be applied to **all** vehicles. I guess you could do what my vfire "support" mod does and replace/alter a function on the vehicle with a spawn hook. 

It would be better though if simfphys had hooks for tinkering or more freedom like LFS does.

**Comment by Blu-x92** [comment]
see #50
