### ISSUE TITLE
[HELP/NOT EXACTLY AN ISSUE] Simfphys x Seat Weapons compatibility.

### ISSUE THREAD

**Issue by Matsilagi** [Blu-x92/simfphys_base#51]
Hey!
Im trying to make this compatible with Seat Weaponizer II / Seat Weapons since i made ArcCW Physical Bullets not hit the car, but i need some help of someone that knows the base better than me (and there is no one better than the creator itself)

So, basically Seat Weapons hijacks into the camera functions of vehicles, and then replaces part of it with its own code, making the viewmodel and positions correct, while in Simfphys, this doesn't work quite well (probably because they use a system entirely different from vehicles)

I tried looking at the code but couldn't find any clues. Any idea where i should start looking at to make them compatible / which functions to look at for overrides?

Here is the Seat Weapons code: https://pastebin.com/0XpgGpBg
And here is a video showing the bug: https://streamable.com/vs1ytp

I don't need anyone to do the entire work for me, just an insight on where i should start reading to then override / hijack. Couldn't find much clues by just searching for View calls and whatnot on all Lua files.

**Comment by Matsilagi** [comment]
Basically, the only issue i need to fix is the viewmodel position being wrong, it has to be centered like on a normal seat.
I'll record a working vs non-working scenario shortly.

**Comment by Matsilagi** [comment]
Basically, i need to know where Simfphys does its camera view stuff on Firstperson and thirdperson to fix the weapon positions and view positions when using the Seat Weapons addon.

**Comment by Blu-x92** [comment]
i think you are experiencing the same viewmodel fov bug as i did:
https://discord.com/channels/565105920414318602/589120351238225940/840575895822925855

Original view code is done in CalcVehicleView:
https://github.com/Blu-x92/simfphys_base/blob/master/lua/simfphys/view.lua#L23

You can overwrite the entire camera behavior by using the calcview hook see: https://wiki.facepunch.com/gmod/GM:CalcView

Armed vehicles use CalcView aswell so you might have to do some trickery to prevent the camera code being run on these vehicles

**Comment by Matsilagi** [comment]
Forwarded for the person to look, might take some time.

**Comment by Blu-x92** [comment]
i think the fov issue has been fixed
https://commits.facepunch.com/387006
