### ISSUE TITLE
Users cant Damage Vehicles spawned by Admins

### ISSUE THREAD

**Issue by BlueSkyCubeGaming** [Blu-x92/simfphys_base#53]
Hello! we pinned down a very annoying issue we have.

When an Admin Spawns a Vehicle that needs Simfphys Base, it cant be damaged by users no matter what, if a user spawns a car and fights another user it works. but as soon as a superadmin spawns it its indestructible to users. 

superadmins can fight other superadmins without issues on the other hand. 

any ideas?

**Comment by Blu-x92** [comment]
check your damage protector / prop protector / admin mod settings. Note that some gamemodes have an integrated damage protector

**Comment by BlueSkyCubeGaming** [comment]
> check your damage protector / prop protector / admin mod settings. Note that some gamemodes have an integrated damage protector

Found it, There was Damage Protection from "Falcos Prop Protection" Really weird thats its soo hidden. anyway. cheers for the tip!
