### ISSUE TITLE
Instant crash when a fast zombie jump attacks a simfphys driver ( x64 )

### ISSUE THREAD

**Issue by StrawWagen** [Blu-x92/simfphys_base#54]
**_x64_** dedicated/singleplayer session instantly crashes when a fast zombie jump attacks a player that's driving a simfphys car.

The issue has been very repeatable for me, I have lots of addons installed so the issue may be a conflict.

After discovering the issue on an x64 dedicated server, I subsequently created a singleplayer session ( x64 ). When I loaded in, I spawned in a simfphys vehicle, then spawned around a dozen fast zombies. I crashed out of the session quickly after I sat in the car's driver seat.

Here's to hoping this issue is repeatable, leave a comment if you can't repeat the issue. Thanks!

**Comment by Blu-x92** [comment]
Can't fix. Had to exclude fast zombies from targeting vehicles. LFS was also affected. Thanks for reporting

**Comment by Blu-x92** [comment]
i close this cuz the reported issue is fixed in https://github.com/Blu-x92/simfphys_base/commit/6d7abaab646bb5a4b597d8b2792172a3844cfcc4 Doubt its fixable from my side

**Comment by Blu-x92** [comment]
https://github.com/Facepunch/garrysmod-issues/issues/4969
hmmmmmmmmm
