### ISSUE TITLE
EyeAngles detour is wrong

### ISSUE THREAD

**Issue by DBotThePony** [Blu-x92/simfphys_base#55]
`EyeAngles` not taking into account `GetParent`'s angles is *exclusively* specific to local `player`. Non-local and serverside *EyeAngles* was never broken.

This detour results `EyeAngles()` always return `Angle(0, 0, 0)` for non-local players inside Simfphys vehicles clientside.

Affected code:
https://github.com/Blu-x92/simfphys_base/blob/6d7abaab646bb5a4b597d8b2792172a3844cfcc4/lua/simfphys/eyeangles_legacy.lua#L14-L28

**Comment by Blu-x92** [comment]
they reverted the changes because it broke too much afaik
