### ISSUE TITLE
Joystick works in SP but not MP

### ISSUE THREAD

**Issue by Vnom** [Blu-x92/simfphys_base#57]
Hello, I have a server that uses Joystick and it works fine in Singleplayer, I can see Simfphys/Simfphys Gears/WAC in there but in Multiplayer all I see is WAC, i've been trying to figure out this issue for multiple days and haven't come up with anything so i'm here now.

**Comment by Blu-x92** [comment]
doesn't look like anyone want's to help with this. I close this issue as i have no plans in further enhancing joystick support but instead would just remove it completely.
