### ISSUE TITLE
Joystick inputs are intermittent (not related to #57)

### ISSUE THREAD

**Issue by RanchTheDeer** [Blu-x92/simfphys_base#58]
When using Simfphys with a joystick using MattJeanes' Joystick Module in singleplayer, no issues occur. However, seemingly randomly on multiplayer servers (I have tested 3 that exhibit this issue), the input mapper menu shows up, I can map controls for Simfphys, however the vehicles don't respond to any input. This is random; I can connect to a server and sometimes it'll work, and others it won't, without any form of indication as to why.
(not related to #57 because the configuration options do show up, its just that Simfphys doesn't respond to inputs).

I have confirmed this is not an issue with the Joystick Module as other addons receive input correctly, such as Wiremod's Joystick Inputs.

**Comment by Blu-x92** [comment]
haven't found time to look into the whole joystick stuff maybe someone else can help with this

**Comment by Blu-x92** [comment]
doesn't look like anyone want's to help with this. I close this issue as i have no plans in further enhancing joystick support but instead would just remove it completely.
