### ISSUE TITLE
Wavs to Oggs

### ISSUE THREAD

**Issue by Python1320** [Blu-x92/simfphys_base#6]
Some waves could be turned to oggs that do not have cue marks as gmod was added an ogg parser. This could lower the filesize at least slightly. I will attempt making this conversion automatically if okay (for those sounds that don't have cue data).

**Comment by Blu-x92** [comment]
i can do this but it won't make much of a difference since there are only about 12 sounds that don't have cue points wich (in total) are less than 1MB
