### ISSUE TITLE
Vehicles keep floating and sometimes don't appear

### ISSUE THREAD

**Issue by MTFSCP** [Blu-x92/simfphys_base#61]
Timer Failed! [Simple][@lua/entities/gmod_sent_vehicle_fphysics_base/spawn.lua (line 360)]
[simfphys Armed Vehicle Pack] ERROR:TRACE FILTER IS INVALID. PLEASE UPDATE SIMFPHYS BASE
ServerLog: [FAdmin] Panzer UnterOffizer Klaus Graf (STEAM_0:1:126596826) Attempted to switch noclip
ServerLog: [FAdmin] Panzer UnterOffizer Klaus Graf (STEAM_0:1:126596826) Entered prop_vehicle_prisoner_pod
ServerLog: [FAdmin] Panzer UnterOffizer Klaus Graf (STEAM_0:1:126596826) exited a prop_vehicle_prisoner_pod
ServerLog: [FAdmin] prop_physics(models/hunter/plates/plate.mdl) Got removed
ServerLog: [FAdmin] prop_physics(models/props_c17/canisterchunk01g.mdl) Got removed
ServerLog: [FAdmin] Panzer UnterOffizer Klaus Graf (STEAM_0:1:126596826) Attempted to switch noclip
ServerLog: [FAdmin] Panzer UnterOffizer Klaus Graf (STEAM_0:1:126596826) Spawned a gmod_sent_vehicle_fphysics_base
ServerLog: [ULX] Panzer UnterOffizer Klaus Graf spawned vehicle models/wt_kingtiger_sla16_main.mdl
Panzer UnterOffizer Klaus Graf spawned vehicle models/wt_kingtiger_sla16_main.mdl
[[simfphys] LUA Vehicles - Base] lua/entities/gmod_sent_vehicle_fphysics_base/spawn.lua:654: attempt to index local 'nocollide' (a nil value)
  1. CreateWheel - lua/entities/gmod_sent_vehicle_fphysics_base/spawn.lua:654
   2. SetupVehicle - lua/entities/gmod_sent_vehicle_fphysics_base/spawn.lua:527
    3. unknown - lua/entities/gmod_sent_vehicle_fphysics_base/spawn.lua:412
Timer Failed! [Simple][@lua/entities/gmod_sent_vehicle_fphysics_base/spawn.lua (line 360)]
[simfphys Armed Vehicle Pack] ERROR:TRACE FILTER IS INVALID. PLEASE UPDATE SIMFPHYS BASE

**Comment by Blu-x92** [comment]
conflict with your admin mod/ spam protection. Nothing i can do from my side
