### ISSUE TITLE
Issue with Sony PS4 con on Linux

### ISSUE THREAD

**Issue by S0LiD-ST4T3** [Blu-x92/simfphys_base#62]
I have a bit of a problem with the mapping on my gamepad...

Moving the left stick, despite being set for steering & air control, ends up moving me out of my seat to some other random seat...

If you have any tips to fix this at all, go ahead and tell me.

**Comment by Blu-x92** [comment]
i dont have linux or a PS4 controler and im not developing the controler addon which is binding the keys. I cant help you with this

**Comment by S0LiD-ST4T3** [comment]
thanks for the clarification then. can you point me in the right direction then?
