### ISSUE TITLE
Hide driver?

### ISSUE THREAD

**Issue by umustbeloggedintododat** [Blu-x92/simfphys_base#63]
Is there a way to hide the driver? I'm making a RC car for simfphys and it looks quite awkward when the driver just sits there like tha
![20211023182754_1](https://user-images.githubusercontent.com/54049600/138573467-15205c08-4bce-428d-a22e-1d9a1d057860.jpg)
t.

**Comment by Blu-x92** [comment]
you need to code this yourself. Hide Driver is just Setting Alpha 0 on the Player and resetting it once you leave the vehicle
