### ISSUE TITLE
 sv_simfphys_devmode  not working

### ISSUE THREAD

**Issue by Rain1950** [Blu-x92/simfphys_base#68]
I tried blocking edit properties and i used  sv_simfphys_devmode 0 in server console. I restarted server but still i can use edit properties on cars, i can add for example nitro. I tried with every usergroup just to be sure but still. Is there any other way to block it? possibly by changing some code/ removing part of it? Or maybe i'm doing something wrong

**Comment by Blu-x92** [comment]
it just disables the edit properties functionality, but the menu is always visible. Try copying the vehicle data usingg the vehicle editor tool to verify if it actually changes the values

**Comment by Rain1950** [comment]
Sadly it works, i can change it and instantly i can see that there is nitro turned on or car smoke is i.e blue. 
Could you help me with CanProperty thing? Should i just create simple script in server -> autostart? or what?

**Comment by Blu-x92** [comment]
sv_simfphys_devmode has been removed in https://github.com/Blu-x92/simfphys_base/commit/dbaf65da238a90df43e77a835f87774c76e7dafb

Its always admin only now
