### ISSUE TITLE
Questions about exiting vehicles

### ISSUE THREAD

**Issue by StanPiPJacobs** [Blu-x92/simfphys_base#71]
1. Is there a way to keep the siren sounds on when player leaves the vehicle?
2. Is there a way to disable engine turning off when player dies while driving? Also when player disconnects while driving the vehicle still has its engine on.

**Comment by Blu-x92** [comment]
1. no
2. only as client setting, not global

**Comment by StanPiPJacobs** [comment]
Ok, thanks
