### ISSUE TITLE
Wheels physics problem on cars under 1.4 tons with 15 and bigger rims

### ISSUE THREAD

**Issue by kaihatsu-dg** [Blu-x92/simfphys_base#74]
If the car is under 1.4 tons with 15 or bigger rims, the wheels go crazy and start jumping when you make a big angle turn or hit  something.
All cvar settings are set to recommended.
![изображение](https://user-images.githubusercontent.com/110659827/183027656-8e99709e-b06c-4fbe-a91d-3ef538819e89.png)

**Comment by Blu-x92** [comment]
Nothing wrong here just retarded suspension settings: Solution: adjust suspension settings.
