### ISSUE TITLE
Wheels hitboxes are not rotated properly

### ISSUE THREAD

**Issue by SpiffyJUNIOR** [Blu-x92/simfphys_base#76]
Wheel physobj's should match the model, but they don't and aren't rotated to match them which results in them being inaccurate. I tested if it was an issue with Simpfhys by creating my own PhysObj with PhysicsInitConvex, which confirmed it was as doing it that way worked. This might be an invalid issue but i'm fairly confident that it's legitimate

Screenshot:
![gmod 2022-10-20 17-36-36](https://user-images.githubusercontent.com/43250660/197089215-923f9e9a-b6ad-480c-b0fd-6df37f4f01fb.png)

**Comment by Blu-x92** [comment]
the wheels are spherical. The method you are using to check the physobject is incorrect.

**Comment by SpiffyJUNIOR** [comment]
> the wheels are spherical. The method you are using to check the physobject is incorrect.
my bad, i should've checked using a better method :(
