### ISSUE TITLE
DrawShadow(false) does not work on wheels and their shadows still draw

### ISSUE THREAD

**Issue by SpiffyJUNIOR** [Blu-x92/simfphys_base#77]
I can see that you tried to disable drawing wheel shadows on [this line](https://github.com/Blu-x92/simfphys_base/blob/master/lua/entities/gmod_sent_vehicle_fphysics_wheel.lua#L33), but it doesn't seem to work as shadows still draw ingame.

Screenshot:
![gmod 2022-10-20 18-23-18](https://user-images.githubusercontent.com/43250660/197089481-6531badc-2337-4840-a03a-72b2e5e2c8f3.png)

**Comment by Blu-x92** [comment]
shadow is disabled for the invisible sphere only. Not for the visual "ghost"-wheel
