### ISSUE TITLE
Lack of EnginePos makes game lag like a bitch.

### ISSUE THREAD

**Issue by mrwallace888** [Blu-x92/simfphys_base#80]
For some reason whenever a Simfphys vehicle doesn't have "EnginePos" defined in its lua file, if you spawn the car in the game lags horribly. Whatever Simfphys is defaulting to when there's no EnginePos is for whatever reason _very_ performance-heavy.

**Comment by Blu-x92** [comment]
there is a logic error in the GetEnginePos function. I will look into this

**Comment by Blu-x92** [comment]
needs testing, but should be fixed
