### ISSUE TITLE
Addon taken off workshop?

### ISSUE THREAD

**Issue by SilverMight** [Blu-x92/simfphys_base#9]
This isn't really a project issue, but the addon was taken off the workshop just about a day ago, removing it from my server. I'm fine using from Git, but is there a reason it was removed?

**Comment by cynaraos** [comment]
https://facepunch.com/showthread.php?t=1583076&p=52814129&viewfull=1#post52814129

**Comment by Blu-x92** [comment]
its back:
http://steamcommunity.com/sharedfiles/filedetails/?id=771487490
